import errorOptions from "../errorOptions";

export const inputBanner = [
    {
        jenisInputan: "input",
        type: "text",
        title: "Banner Name",
        name: "banner_name",
        placeholder: "your banner name",
        error: "banner_name",
        addOptionError: errorOptions.banner_name,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "file",
        title: "Banner Image",
        name: "banner_img",
        error: "banner_img",
        addOptionError: errorOptions.banner_img,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "date",
        title: "Start Date",
        name: "start_date_banner",
        error: "start_date_banner",
        addOptionError: errorOptions.start_date_banner,
        grid: 6,
    },
    {
        jenisInputan: "input",
        type: "date",
        title: "End Date",
        name: "end_date_banner",
        error: "end_date_banner",
        addOptionError: errorOptions.end_date_banner,
        grid: 6,
    },
    // {
    //     jenisInputan: "input",
    //     type: "checkbox",
    //     title: "Click to Activate",
    //     name: "status",
    //     grid: 12,
    // },
];

export const inputEditBanner = (data) => {
    return [
        {
            jenisInputan: "hidden",
            type: "text",
            name: "id",
            defaultValue: data.id,
            grid: 12,
        },
        {
            jenisInputan: "input",
            type: "text",
            title: "Banner Name",
            name: "banner_name",
            placeholder: "your banner name",
            error: "banner_name",
            addOptionError: errorOptions.banner_name,
            defaultValue: data.banner_name,
            grid: 12,
        },
        {
            jenisInputan: "input",
            type: "file",
            title: "Banner Image",
            name: "banner_img",
            error: "banner_img",
            // addOptionError: errorOptions.banner_img,
            defaultValue: data.banner_img,
            grid: 12,
        },
        {
            jenisInputan: "input",
            type: "date",
            title: "Start Date",
            name: "start_date_banner",
            error: "start_date_banner",
            addOptionError: errorOptions.start_date_banner,
            defaultValue: data.start_date_banner,
            grid: 6,
        },
        {
            jenisInputan: "input",
            type: "date",
            title: "End Date",
            name: "end_date_banner",
            error: "end_date_banner",
            addOptionError: errorOptions.end_date_banner,
            defaultValue: data.end_date_banner,
            grid: 6,
        },
        {
            jenisInputan: "input",
            type: "checkbox",
            title: "Click to Activate",
            name: "status",
            defaultValue: data.status,
            grid: 12,
        },
    ];
};
