import errorOptions from "../errorOptions";

export const inputCity = (datas) => [
    {
        jenisInputan: "input",
        type: "select",
        title: "Province",
        options: datas.map((data) => ({
            value: data.id,
            label: data.province_name,
        })),
        name: "id_province",
        error: "id_province",
        addOptionError: errorOptions.id_province,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "City Code",
        name: "city_code",
        placeholder: "your city code",
        error: "city_code",
        addOptionError: errorOptions.city_code,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "City Name",
        name: "city_name",
        placeholder: "your city name",
        error: "city_name",
        addOptionError: errorOptions.city_name,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "checkbox",
        title: "Click to Activate",
        name: "status",
        grid: 12,
    },
];

export const inputEditCity = (selectData, defaultValue) => [
    {
        jenisInputan: "input",
        type: "select",
        title: "Province",
        options: selectData,
        name: "id_province",
        error: "id_province",
        addOptionError: errorOptions.id_province,
        defaultValue: defaultValue.id_province,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "City Code",
        name: "city_code",
        placeholder: "your city code",
        error: "city_code",
        addOptionError: errorOptions.city_code,
        defaultValue: defaultValue.city_code,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "City Name",
        name: "city_name",
        placeholder: "your city name",
        error: "city_name",
        addOptionError: errorOptions.city_name,
        defaultValue: defaultValue.city_name,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "checkbox",
        title: "Click to Activate",
        name: "status",
        defaultValue: defaultValue.status,
        grid: 12,
    },
];
