import errorOptions from "../errorOptions";

export const inputFilms = [
    {
        jenisInputan: "input",
        type: "text",
        title: "Film Name",
        name: "nama_film",
        placeholder: "your film name",
        error: "nama_film",
        addOptionError: errorOptions.nama_film,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Trailer Film",
        name: "trailer_film",
        placeholder: "your trailer film",
        error: "trailer_film",
        addOptionError: errorOptions.trailer_film,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "file",
        title: "Poster Film",
        name: "poster_film",
        error: "poster_film",
        addOptionError: errorOptions.poster_film,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "textarea",
        title: "Sinopsis Film",
        name: "sinopsis_film_id",
        placeholder: "your sinopsis film",
        error: "sinopsis_film_id",
        addOptionError: errorOptions.sinopsis_film_id,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "checkbox",
        title: "Click to Activate",
        name: "status",
        grid: 12,
    },
];

export const inputEditFilms = (data) => [
    {
        jenisInputan: "hidden",
        type: "text",
        name: "id",
        defaultValue: data.id,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Film Name",
        name: "nama_film",
        placeholder: "your film name",
        error: "nama_film",
        addOptionError: errorOptions.nama_film,
        defaultValue: data.nama_film,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Trailer Film",
        name: "trailer_film",
        placeholder: "your trailer film",
        error: "trailer_film",
        addOptionError: errorOptions.trailer_film,
        defaultValue: data.trailer_film,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "file",
        title: "Poster Film",
        name: "poster_film",
        error: "poster_film",
        addOptionError: errorOptions.poster_film,
        defaultValue: data.poster_film,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "textarea",
        title: "Sinopsis Film",
        name: "sinopsis_film_id",
        placeholder: "your sinopsis film",
        error: "sinopsis_film_id",
        addOptionError: errorOptions.sinopsis_film_id,
        defaultValue: data.sinopsis_film_id,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "checkbox",
        title: "Click to Activate",
        name: "status",
        defaultValue: data.status,
        grid: 12,
    },
];
