import errorOptions from "../errorOptions";

export const inputOffice = (datas) => [
    {
        jenisInputan: "input",
        type: "select",
        title: "City",
        options: datas.map((data) => ({
            value: data.id,
            label: data.city_name,
        })),
        name: "id_city",
        error: "id_city",
        addOptionError: errorOptions.id_city,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Office Name",
        name: "office_name",
        placeholder: "your office name",
        error: "office_name",
        addOptionError: errorOptions.office_name,
        grid: 12,
    },
    {
        jeniInputan: "input",
        type: "text",
        title: "Address",
        name: "address",
        placeholder: "your address",
        error: "address",
        addOptionError: errorOptions.address,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Instagram",
        name: "ig",
        placeholder: "your instagram",
        error: "ig",
        addOptionError: errorOptions.ig,
        grid: 6,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Facebook",
        name: "fb",
        placeholder: "your facebook",
        error: "fb",
        addOptionError: errorOptions.fb,
        grid: 6,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "X",
        name: "x",
        placeholder: "your x",
        error: "x",
        addOptionError: errorOptions.x,
        grid: 6,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Youtube",
        name: "yt",
        placeholder: "your youtube",
        error: "yt",
        addOptionError: errorOptions.yt,
        grid: 6,
    },
    // {
    //     jenisInputan: "input",
    //     type: "checkbox",
    //     title: "Click to Activate",
    //     name: "status",
    //     grid: 12,
    // },
];

export const inputEditOffice = (selectData, defaultValue) => [
    {
        jenisInputan: "hidden",
        type: "text",
        name: "id",
        defaultValue: defaultValue.id,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "select",
        title: "City",
        options: selectData,
        name: "id_city",
        error: "id_city",
        addOptionError: errorOptions.id_city,
        defaultValue: defaultValue.id_city,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Office Name",
        name: "office_name",
        placeholder: "your office name",
        error: "office_name",
        addOptionError: errorOptions.office_name,
        defaultValue: defaultValue.office_name,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Address",
        name: "address",
        placeholder: "your address",
        error: "address",
        addOptionError: errorOptions.address,
        defaultValue: defaultValue.address,
        grid: 12,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Instagram",
        name: "ig",
        placeholder: "your instagram",
        error: "ig",
        addOptionError: errorOptions.ig,
        defaultValue: defaultValue.ig,
        grid: 6,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Facebook",
        name: "fb",
        placeholder: "your facebook",
        error: "fb",
        addOptionError: errorOptions.fb,
        defaultValue: defaultValue.fb,
        grid: 6,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "X",
        name: "x",
        placeholder: "your x",
        error: "x",
        addOptionError: errorOptions.x,
        defaultValue: defaultValue.x,
        grid: 6,
    },
    {
        jenisInputan: "input",
        type: "text",
        title: "Youtube",
        name: "yt",
        placeholder: "your youtube",
        error: "yt",
        addOptionError: errorOptions.yt,
        defaultValue: defaultValue.yt,
        grid: 6,
    },
    {
        jenisInputan: "input",
        type: "checkbox",
        title: "Click to Activate",
        name: "status",
        defaultValue: defaultValue.status,
        grid: 12,
    },
];
