import { FaEye } from "react-icons/fa";
import { errorOptions } from "../PatternError";

export const inputRegister = [
  {
    jenisInput: "input",
    placeholder: "Jhon Doe",
    type: "text",
    title: "Username",
    name: "username",
    className: "",
    grid: 12,
    addOptionError: errorOptions.username,
    error: "username",
  },

  {
    jenisInput: "input",
    placeholder: "jhon.doe@email.com",
    type: "email",
    title: "E-Mail",
    name: "email",
    className: "",
    grid: 12,
    addOptionError: errorOptions.email,
    error: "email",
  },
  {
    jenisInput: "input",
    placeholder: "0813xxxx",
    type: "number",
    grid: 12,
    title: "Nomor Telp",
    name: "phone_number",
    className: "",
    addOptionError: errorOptions.phone_number,
    error: "phone_number",
  },
  {
    jenisInput: "input",
    placeholder: "*******",
    type: "password",
    grid: 6,
    title: "Password",
    name: "user_password_new",
    className: "",
    icon: FaEye,
    onClick: true,
    addOptionError: errorOptions.user_password_new,
    error: "user_password_new",
  },
  {
    jenisInput: "input",
    placeholder: "*******",
    type: "password",
    grid: 6,
    title: "Password",
    name: "user_password_new_confirm",
    className: "",
    icon: FaEye,
    onClick: true,
    addOptionError: errorOptions.user_password_new_confirm,
    error: "user_password_new_confirm",
  },
];
