/** @format */

import { errorOptions } from "../error";

export const inputAddArticle = (articleCategory) => [
  {
    labelText: "Article Title EN (English)",
    name: "article_title_en",
    type: "text",
    optionError: errorOptions.article_title,
    grid: 6,
  },
  {
    labelText: "Article Title ID (Bahasa)",
    name: "article_title_id",
    type: "text",
    optionError: errorOptions.article_title,
    grid: 6,
  },
  {
    labelText: "Article Slug EN (English)",
    name: "article_slug_en",
    type: "text",
    optionError: errorOptions.article_slug,
    grid: 4,
  },
  {
    labelText: "Article Slug ID (Bahasa)",
    name: "article_slug_id",
    type: "text",
    optionError: errorOptions.article_slug,
    grid: 4,
  },
  {
    labelText: "Article Category",
    name: "id_article_category",
    type: "select",
    optionError: errorOptions.select_category,
    options: articleCategory,
    grid: 4,
  },
  {
    labelText: "Article Image",
    name: "article_img",
    type: "file",
    optionError: errorOptions.article_img,
    className: "w-full h-[400px]",
    grid: 8,
  },
  {
    labelText: "Thumbnail Article Image",
    name: "article_thumbnail_img",
    type: "file",
    optionError: errorOptions.article_thumbnail_img,
    className: "w-full h-[400px]",
    grid: 4,
  },
  {
    labelText: "Thumbnail Article Content EN (English)",
    name: "article_thumbnail_content_en",
    type: "textarea",
    optionError: errorOptions.article_thumbnail_content,
    rows: 5,
    grid: 6,
  },
  {
    labelText: "Thumbnail Article Content ID (Bahasa)",
    name: "article_thumbnail_content_id",
    type: "textarea",
    optionError: errorOptions.article_thumbnail_content,
    rows: 5,
    grid: 6,
  },
  {
    labelText: "Article Content EN (English)",
    name: "article_content_en",
    type: "editor_about",
    optionError: errorOptions.article_content,
    className: "h-[500px] mb-28 md:mb-36 xl:mb-20",
    grid: 6,
  },
  {
    labelText: "Article Content ID (Bahasa)",
    name: "article_content_id",
    type: "editor_about",
    optionError: errorOptions.article_content,
    className: "h-[500px] mb-28 md:mb-36 xl:mb-20",
    grid: 6,
  },
];

export const inputEditArticle = (articleCategory, datasDetailArticle) => [
  {
    labelText: "Article Title EN (English)",
    name: "article_title_en",
    type: "text",
    optionError: errorOptions.article_title,
    grid: 6,
    defaultValue: datasDetailArticle.article_title_en,
  },
  {
    labelText: "Article Title ID (Bahasa)",
    name: "article_title_id",
    type: "text",
    optionError: errorOptions.article_title,
    grid: 6,
    defaultValue: datasDetailArticle.article_title_id,
  },
  {
    labelText: "Article Slug EN (English)",
    name: "article_slug_en",
    type: "text",
    optionError: errorOptions.article_slug,
    grid: 4,
    defaultValue: datasDetailArticle.article_slug_en,
  },
  {
    labelText: "Article Slug ID (Bahasa)",
    name: "article_slug_id",
    type: "text",
    optionError: errorOptions.article_slug,
    grid: 4,
    defaultValue: datasDetailArticle.article_slug_id,
  },
  {
    labelText: "Article Category",
    name: "id_article_category",
    type: "select",
    optionError: errorOptions.select_category,
    options: articleCategory,
    defaultValue: datasDetailArticle.id_article_category,
    grid: 4,
  },
  {
    labelText: "Article Image",
    name: "article_img",
    type: "file",
    className: "w-full h-[400px]",
    defaultValue: datasDetailArticle.article_img,
    grid: 8,
  },
  {
    labelText: "Thumbnail Article Image",
    name: "article_thumbnail_img",
    type: "file",
    className: "w-full h-[400px]",
    defaultValue: datasDetailArticle.article_thumbnail_img,
    grid: 4,
  },
  {
    labelText: "Thumbnail Article Content EN (English)",
    name: "article_thumbnail_content_en",
    type: "textarea",
    optionError: errorOptions.article_thumbnail_content,
    rows: 5,
    grid: 6,
    defaultValue: datasDetailArticle.article_thumbnail_content_en,
  },
  {
    labelText: "Thumbnail Article Content ID (Bahasa)",
    name: "article_thumbnail_content_id",
    type: "textarea",
    optionError: errorOptions.article_thumbnail_content,
    rows: 5,
    grid: 6,
    defaultValue: datasDetailArticle.article_thumbnail_content_id,
  },
  {
    labelText: "Article Content EN (English)",
    name: "article_content_en",
    type: "editor_about",
    optionError: errorOptions.article_content,
    className: "h-[500px] mb-28 md:mb-36 xl:mb-20",
    grid: 6,
    defaultValue: datasDetailArticle.article_content_en,
  },
  {
    labelText: "Article Content ID (Bahasa)",
    name: "article_content_id",
    type: "editor_about",
    optionError: errorOptions.article_content,
    className: "h-[500px] mb-28 md:mb-36 xl:mb-20",
    grid: 6,
    defaultValue: datasDetailArticle.article_content_id,
  },
];

export const inputAddArticleCategories = [
  {
    labelText: "Category Name EN (English)",
    name: "article_category_name_en",
    type: "text",
    optionError: errorOptions.category_name,
    grid: 12,
  },
  {
    labelText: "Category Name ID (Bahasa)",
    name: "article_category_name_id",
    type: "text",
    optionError: errorOptions.category_name,
    grid: 12,
  },
  {
    labelText: "Category Name ID",
    name: "article_category_name_id",
    type: "text",
    // optionError: errorOptions.category_name,
    grid: 12,
  },
];

export const inputEditArticleCategories = (defaultValue) => [
  {
    labelText: "Category Name EN (English)",
    name: "article_category_name_en",
    type: "text",
    optionError: errorOptions.category_name,
    grid: 12,
    defaultValue: defaultValue.article_category_name_en,
  },
  {
    labelText: "Category Name ID (Bahasa)",
    name: "article_category_name_id",
    type: "text",
    optionError: errorOptions.category_name,
    grid: 12,
    defaultValue: defaultValue.article_category_name_id,
  },
  {
    labelText: "Status",
    name: "status",
    type: "select",
    optionDisabledText: "Select Status",
    defaultValue: defaultValue.status,
    options: [
      { label: "Active", value: true },
      { label: "Inactive", value: false },
    ],
    grid: 12,
  },
];
